name: Lint Commit Messages
on: [push, pull_request]
  branches:
    - main
    - dev

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wagoid/commitlint-github-action@v5
      - uses: ./.github/workflows/commitlint.config.js