name: release-please
on:
  pull_request:
    tags:
      - "v*"
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: python
          package-name: release-please-action
          repo-token: ${{ secrets.GITHUB_TOKEN }}